# Generated by Django 2.2 on 2019-06-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='employee',
        ),
    ]
