# Generated by Django 2.2.1 on 2019-09-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('authors', models.CharField(max_length=255, verbose_name='Авторы')),
                ('publishing', models.CharField(max_length=100, verbose_name='Издательство')),
                ('section', models.TextField(verbose_name='Раздел')),
                ('code', models.CharField(max_length=100, verbose_name='Шифр книги')),
                ('active', models.BooleanField(default=True, verbose_name='Наличие книги')),
                ('registration_date', models.DateField(null=True, verbose_name='Дата издательства')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалена')),
                ('deleted_at', models.DateField(null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='Название')),
                ('people_count', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Читательский зал',
                'verbose_name_plural': 'Читательские залы',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_ticket', models.IntegerField(verbose_name='Номер читательского билета')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport_number', models.IntegerField(verbose_name='Номер пасспорта')),
                ('birthday', models.DateField(verbose_name='День рождение')),
                ('addr', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('science_degree', models.BooleanField(verbose_name='Ученая степень')),
                ('active', models.BooleanField(default=True, verbose_name='Записан читатель или нет')),
                ('deleted_at', models.DateField(null=True, verbose_name='Дата удаления')),
                ('registration_date', models.DateField(null=True, verbose_name='Дата регистрации')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Educations', verbose_name='Образование')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.ReadingRoom', verbose_name='Читательский зал')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='BookReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата выдачи книги')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата книги')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Книга')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Информация о закрепленной книги',
                'verbose_name_plural': 'Информация о закрепленных книгах',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.ReadingRoom', verbose_name='Читательский зал'),
        ),
    ]
